// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_commerce.Models;

#nullable disable

namespace e_commerce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250902114620_SliderlarTableFix")]
    partial class SliderlarTableFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("e_commerce.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdi = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAdi = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAdi = "Giyim",
                            Url = "giyim"
                        },
                        new
                        {
                            Id = 5,
                            KategoriAdi = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 6,
                            KategoriAdi = "Kategori 1",
                            Url = "kategori-1"
                        },
                        new
                        {
                            Id = 7,
                            KategoriAdi = "Kategori 2",
                            Url = "kategori-2"
                        },
                        new
                        {
                            Id = 8,
                            KategoriAdi = "Kategori 3",
                            Url = "kategori-3"
                        },
                        new
                        {
                            Id = 9,
                            KategoriAdi = "Kategori 4",
                            Url = "kategori-4"
                        });
                });

            modelBuilder.Entity("e_commerce.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sliderlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Slider 1 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 1 Başlık",
                            Index = 0,
                            Resim = "slider-1.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Slider 2 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 2 Başlık",
                            Index = 1,
                            Resim = "slider-2.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Slider 3 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 3 Başlık",
                            Index = 2,
                            Resim = "slider-3.jpeg"
                        });
                });

            modelBuilder.Entity("e_commerce.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Apple Watch 8 41mm Alüminyum Kasa ve Spor Kordon",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 15000.0,
                            KategoriId = 1,
                            Resim = "1.jpeg",
                            UrunAdi = "Apple Watch 8"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Apple Watch 8 41mm Alüminyum Kasa ve Spor Kordon",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 8000.0,
                            KategoriId = 2,
                            Resim = "2.jpeg",
                            UrunAdi = "Apple Watch 9"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Apple Watch 8 41mm Alüminyum Kasa ve Spor Kordon",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 6000.0,
                            KategoriId = 3,
                            Resim = "3.jpeg",
                            UrunAdi = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Apple Watch 8 41mm Alüminyum Kasa ve Spor Kordon",
                            Aktif = false,
                            Anasayfa = false,
                            Fiyat = 1200.0,
                            KategoriId = 4,
                            Resim = "4.jpeg",
                            UrunAdi = "Apple Watch 11"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Apple Watch 8 41mm Alüminyum Kasa ve Spor Kordon",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 3500.0,
                            KategoriId = 4,
                            Resim = "5.jpeg",
                            UrunAdi = "Apple Watch 12"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Apple Watch 8 41mm Alüminyum Kasa ve Spor Kordon",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 3500.0,
                            KategoriId = 2,
                            Resim = "6.jpeg",
                            UrunAdi = "Apple Watch 12"
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Apple Watch 8 41mm Alüminyum Kasa ve Spor Kordon",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 90000.0,
                            KategoriId = 1,
                            Resim = "7.jpeg",
                            UrunAdi = "Apple Watch 13"
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Apple Watch 8 41mm Alüminyum Kasa ve Spor Kordon",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 80500.0,
                            KategoriId = 5,
                            Resim = "8.jpeg",
                            UrunAdi = "Apple Watch 14"
                        });
                });

            modelBuilder.Entity("e_commerce.Models.Urun", b =>
                {
                    b.HasOne("e_commerce.Models.Kategori", "kategori")
                        .WithMany("Uruns")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kategori");
                });

            modelBuilder.Entity("e_commerce.Models.Kategori", b =>
                {
                    b.Navigation("Uruns");
                });
#pragma warning restore 612, 618
        }
    }
}
